from flask import Blueprint, request, jsonify
import requests
import time
from datetime import datetime
import math

protein_bp = Blueprint('protein', __name__)

# Cache configuration
PREDICTION_CACHE = {}
CACHE_TTL = 3600  # 1 hour in seconds

def calculate_plDDT(pdb_data):
    """Identical to original calculatePLDDT() converted to Python"""
    try:
        if not pdb_data or not isinstance(pdb_data, str):
            return 0
            
        lines = pdb_data.split('\n')
        total = count = 0
        min_val = float('inf')
        max_val = float('-inf')
        
        for line in lines:
            if line.startswith('ATOM'):
                try:
                    b_factor = float(line[60:66].strip())
                    total += b_factor
                    count += 1
                    min_val = min(min_val, b_factor)
                    max_val = max(max_val, b_factor)
                except:
                    continue
        
        return round(total / count, 2) if count > 0 else 0
    except Exception as e:
        print(f"Error calculating plDDT: {e}")
        return 0

def predict_secondary_structure(pdb_data):
    """Full version identical to original predictSecondaryStructure()"""
    try:
        lines = pdb_data.split('\n')
        structure = []
        ca_atoms = []
        
        # First pass: collect all CA atoms
        for line in lines:
            if line.startswith('ATOM') and line[12:16].strip() == 'CA':
                ca_atoms.append({
                    'x': float(line[30:38].strip()),
                    'y': float(line[38:46].strip()),
                    'z': float(line[46:54].strip()),
                    'resNum': int(line[22:26].strip()),
                    'resName': line[17:20].strip(),
                    'chain': line[21:22].strip(),
                    'bFactor': float(line[60:66].strip())
                })
        
        # Second pass: predict secondary structure
        for i in range(len(ca_atoms)):
            current = ca_atoms[i]
            prev = ca_atoms[i-1] if i > 0 else None
            prev_prev = ca_atoms[i-2] if i > 1 else None
            
            ss_type = 'C'  # Default to coil
            
            if prev_prev and prev and i < len(ca_atoms) - 1:
                next_atom = ca_atoms[i+1]
                
                # Calculate phi and psi angles
                phi = calculate_dihedral_angle(prev_prev, prev, current, next_atom)
                next_next = ca_atoms[i+2] if i < len(ca_atoms) - 2 else None
                psi = calculate_dihedral_angle(prev, current, next_atom, next_next)
                
                # Helix detection
                if -120 < phi < -30 and -70 < psi < -20:
                    ss_type = 'H'
                # Sheet detection
                elif (phi < -90 and psi > 90) or (phi > 90 and psi < -90):
                    ss_type = 'E'
                
                # Fallback to B-factor
                if ss_type == 'C' and current['bFactor'] > 0:
                    if current['bFactor'] > 70:
                        ss_type = 'H'
                    elif current['bFactor'] > 50:
                        ss_type = 'E'
            
            structure.append({
                'residue': current['resName'],
                'chain': current['chain'],
                'resNum': current['resNum'],
                'ssType': ss_type
            })
        
        return structure
    except Exception as e:
        print(f"Error predicting secondary structure: {e}")
        return None

def calculate_dihedral_angle(a, b, c, d):
    """Identical to original calculateDihedralAngle()"""
    if not all([a, b, c, d]):
        return 0
    
    b1 = {'x': b['x']-a['x'], 'y': b['y']-a['y'], 'z': b['z']-a['z']}
    b2 = {'x': c['x']-b['x'], 'y': c['y']-b['y'], 'z': c['z']-b['z']}
    b3 = {'x': d['x']-c['x'], 'y': d['y']-c['y'], 'z': d['z']-c['z']}
    
    n1 = cross_product(b1, b2)
    n2 = cross_product(b2, b3)
    
    m1 = cross_product(n1, b2)
    x = dot_product(n1, n2)
    y = dot_product(m1, n2)
    
    return math.degrees(math.atan2(y, x))

def cross_product(a, b):
    """Identical to original crossProduct()"""
    return {
        'x': a['y'] * b['z'] - a['z'] * b['y'],
        'y': a['z'] * b['x'] - a['x'] * b['z'],
        'z': a['x'] * b['y'] - a['y'] * b['x']
    }

def dot_product(a, b):
    """Identical to original dotProduct()"""
    return a['x'] * b['x'] + a['y'] * b['y'] + a['z'] * b['z']

def generate_enhanced_pdb(sequence):
    """Identical to original generateEnhancedPDB()"""
    pdb = "HEADER    GENERATED PROTEIN STRUCTURE\n"
    pdb += "TITLE     PREDICTED STRUCTURE\n"
    pdb += "REMARK    GENERATED BY FALLBACK ALGORITHM\n"
    
    atom_num = 1
    residue_num = 1
    chain = 'A'
    
    for idx, aa in enumerate(sequence):
        is_helix = idx % 3 == 0
        is_sheet = idx % 5 == 0
        
        x = idx * 1.5
        y = math.sin(idx * 0.5) * 5 if is_helix else math.sin(idx * 0.3) * 3 if is_sheet else 0
        z = math.cos(idx * 0.5) * 5 if is_helix else math.cos(idx * 0.3) * 3 if is_sheet else 0
        
        if idx == 0 or sequence[idx-1] != aa:
            pdb += f"SEQRES   1 {chain}  {len(sequence)}  {aa}\n"
        
        pdb += f"ATOM  {atom_num:5}  N   {aa} {chain}{residue_num:4}    {x:8.3f}{y:8.3f}{z:8.3f}  1.00 {80 if is_helix else 70 if is_sheet else 60}.00           N\n"
        atom_num += 1
        
        pdb += f"ATOM  {atom_num:5}  CA  {aa} {chain}{residue_num:4}    {x+1.0:8.3f}{y+0.5:8.3f}{z+0.5:8.3f}  1.00 {80 if is_helix else 70 if is_sheet else 60}.00           C\n"
        atom_num += 1
        
        residue_num += 1
    
    # Add connectivity
    for i in range(1, residue_num):
        pdb += f"CONECT {i*2-1:4} {i*2:4}\n"
        if i > 1:
            pdb += f"CONECT {i*2-3:4} {i*2-1:4}\n"
    
    pdb += "TER\nEND\n"
    return pdb

@protein_bp.route('/predict-protein', methods=['POST'])
def predict_protein():
    """Complete endpoint matching original functionality"""
    try:
        data = request.get_json()
        sequence = data.get('sequence', '').strip()
        
        # Validation
        if not sequence or not isinstance(sequence, str):
            return jsonify({'error': 'Sequence is required and must be a string'}), 400
            
        if len(sequence) < 10:
            return jsonify({
                'error': 'Sequence too short',
                'details': 'Minimum 10 amino acids required'
            }), 400
            
        if len(sequence) > 1000:
            return jsonify({
                'error': 'Sequence too long',
                'details': 'Maximum 1000 amino acids allowed'
            }), 400

        # Check cache
        cached = PREDICTION_CACHE.get(sequence)
        if cached and (time.time() - cached['timestamp'] < CACHE_TTL):
            return jsonify(cached['data'])

        # Try ESMFold API with retry logic
        pdb_data = None
        source = 'esmfold'
        attempts = 0
        max_attempts = 2
        
        while attempts < max_attempts:
            try:
                response = requests.post(
                    'https://api.esmatlas.com/foldSequence/v1/pdb/',
                    data=sequence,
                    headers={
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'Accept-Encoding': 'gzip, deflate, br'
                    },
                    timeout=120
                )
                if response.status_code == 200:
                    pdb_data = response.text
                    break
            except:
                attempts += 1
                if attempts >= max_attempts:
                    pdb_data = generate_enhanced_pdb(sequence)
                    source = 'fallback'
                else:
                    time.sleep(2)

        # Prepare response
        result = {
            'pdb': pdb_data,
            'plDDT': calculate_plDDT(pdb_data),
            'secondaryStructure': predict_secondary_structure(pdb_data),
            'source': source,
            'timestamp': datetime.now().isoformat()
        }
        
        # Cache result
        PREDICTION_CACHE[sequence] = {
            'data': result,
            'timestamp': time.time()
        }
        
        return jsonify(result)
        
    except Exception as e:
        return jsonify({
            'error': 'Prediction failed',
            'details': str(e),
            'suggestion': 'Please try again with a different sequence'
        }), 500